-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "buyerGSTIN" TEXT,
ADD COLUMN     "cgstAmount" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "cgstRate" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "invoiceType" TEXT NOT NULL DEFAULT 'EXPORT',
ADD COLUMN     "sgstAmount" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "sgstRate" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "taxableAmount" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "totalGSTAmount" DECIMAL(65,30) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "InvoiceItem" ADD COLUMN     "cgstAmount" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "gstRate" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "igstAmount" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "sgstAmount" DECIMAL(65,30) NOT NULL DEFAULT 0;
